### ISSUE TITLE
分享文件夹报错

### ISSUE THREAD

**Issue by Ekkone** [1943time/bluestone-service#4]
markdown文件夹内容链接：https://github.com/ruanyf/weekly
分享单个markdown文件正常，分享整个文件夹报错：
![image](https://github.com/1943time/bluestone-service/assets/38444906/48657b65-d594-45dc-b195-b383613fdd1c)
服务端报错日志：

> bluestone_1  |  ⨯ PrismaClientKnownRequestError:
bluestone_1  | Invalid `prisma.book.update()` invocation:
bluestone_1  | Transaction API error: Transaction already closed: A query cannot be executed on an expired transaction. The timeout for this transaction was 5000 ms, however 5232 ms passed since the start of the transaction. Consider increasing the interactive transaction timeout or doing less work in the transaction.
bluestone_1  |     at Cn.handleRequestError (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:6817)
bluestone_1  |     at Cn.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:6206)
bluestone_1  |     at Cn.request (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:5926)
bluestone_1  |     at async l (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:128:9968)
bluestone_1  |     at async /app/.next/server/app/api/book/route.js:1:2979
bluestone_1  |     at async Proxy._transactionWithCallback (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:128:8631)
bluestone_1  |     at async g (/app/.next/server/app/api/book/route.js:1:2940)
bluestone_1  |     at async /app/node_modules/.pnpm/next@14.1.3_react-dom@18.0.0_react@18.0.0_sass@1.69.5/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
bluestone_1  |     at async eI.execute (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.0.0_react@18.0.0_sass@1.69.5/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
bluestone_1  |     at async eI.handle (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.0.0_react@18.0.0_sass@1.69.5/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737) {
bluestone_1  |   code: 'P2028',
bluestone_1  |   clientVersion: '5.5.2',
bluestone_1  |   meta: {
bluestone_1  |     error: 'Transaction already closed: A query cannot be executed on an expired transaction. The timeout for this transaction was 5000 ms, however 5232 ms passed since the start of the transaction. Consider increasing the interactive transaction timeout or doing less work in the transaction.'
bluestone_1  |   }
bluestone_1  | }
bluestone_1  |  ⨯ PrismaClientKnownRequestError:
bluestone_1  | Invalid `prisma.book.update()` invocation:
bluestone_1  | Transaction API error: Transaction already closed: A query cannot be executed on an expired transaction. The timeout for this transaction was 5000 ms, however 5239 ms passed since the start of the transaction. Consider increasing the interactive transaction timeout or doing less work in the transaction.
bluestone_1  |     at Cn.handleRequestError (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:6817)
bluestone_1  |     at Cn.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:6206)
bluestone_1  |     at Cn.request (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:5926)
bluestone_1  |     at async l (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:128:9968)
bluestone_1  |     at async /app/.next/server/app/api/book/route.js:1:2979
bluestone_1  |     at async Proxy._transactionWithCallback (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:128:8631)
bluestone_1  |     at async g (/app/.next/server/app/api/book/route.js:1:2940)
bluestone_1  |     at async /app/node_modules/.pnpm/next@14.1.3_react-dom@18.0.0_react@18.0.0_sass@1.69.5/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
bluestone_1  |     at async eI.execute (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.0.0_react@18.0.0_sass@1.69.5/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
bluestone_1  |     at async eI.handle (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.0.0_react@18.0.0_sass@1.69.5/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737) {
bluestone_1  |   code: 'P2028',
bluestone_1  |   clientVersion: '5.5.2',
bluestone_1  |   meta: {
bluestone_1  |     error: 'Transaction already closed: A query cannot be executed on an expired transaction. The timeout for this transaction was 5000 ms, however 5239 ms passed since the start of the transaction. Consider increasing the interactive transaction timeout or doing less work in the transaction.'
bluestone_1  |   }
bluestone_1  | }
bluestone_1  |  ⨯ PrismaClientKnownRequestError:
bluestone_1  | Invalid `prisma.book.update()` invocation:
bluestone_1  | Transaction API error: Transaction already closed: A query cannot be executed on an expired transaction. The timeout for this transaction was 5000 ms, however 5292 ms passed since the start of the transaction. Consider increasing the interactive transaction timeout or doing less work in the transaction.
bluestone_1  |     at Cn.handleRequestError (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:6817)
bluestone_1  |     at Cn.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:6206)
bluestone_1  |     at Cn.request (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:5926)
bluestone_1  |     at async l (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:128:9968)
bluestone_1  |     at async /app/.next/server/app/api/book/route.js:1:2979
bluestone_1  |     at async Proxy._transactionWithCallback (/app/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:128:8631)
bluestone_1  |     at async g (/app/.next/server/app/api/book/route.js:1:2940)
bluestone_1  |     at async /app/node_modules/.pnpm/next@14.1.3_react-dom@18.0.0_react@18.0.0_sass@1.69.5/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
bluestone_1  |     at async eI.execute (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.0.0_react@18.0.0_sass@1.69.5/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
bluestone_1  |     at async eI.handle (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.0.0_react@18.0.0_sass@1.69.5/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737) {
bluestone_1  |   code: 'P2028',
bluestone_1  |   clientVersion: '5.5.2',
bluestone_1  |   meta: {
bluestone_1  |     error: 'Transaction already closed: A query cannot be executed on an expired transaction. The timeout for this transaction was 5000 ms, however 5292 ms passed since the start of the transaction. Consider increasing the interactive transaction timeout or doing less work in the transaction.'
bluestone_1  |   }
bluestone_1  | }

**Comment by Ekkone** [comment]
测试了一个简单内容的文件夹没有问题，应该是这个文件夹内容过多或者有些格式不支持？麻烦用我前面提供的github链接测试一下是否正常

**Comment by 1943time** [comment]
http://47.76.123.117:3006/book/weakly 我这边可以发布，猜测可能是因为前端请求超时设置的比较短导致的，或者你是否使用了cloudflare代理，这个文档体积超过了cloudflare的上限。

**Comment by Ekkone** [comment]
好吧，那应该是其他问题导致的
